import Head from 'next/head'
import {ApolloClient, ApolloQueryResult, InMemoryCache} from '@apollo/client';
import {RestLink} from 'apollo-link-rest';
import {gql} from '@apollo/client';
import {JsonApiLink} from "apollo-link-json-api";
import {useEffect, useState} from "react";
import React from 'react';
import {useQuery} from '@apollo/client';
import client from '../lib/withApollo'
import {booksQuery as query} from '../queries/booksQuery'
import Book from "../components/Book";
import {Box} from "@material-ui/core";
import {Grid} from "@material-ui/core";
import Search from "../components/Search";
import Typography from '@material-ui/core/Typography';
import { makeStyles, Theme, createStyles } from '@material-ui/core/styles';

const useStyles = makeStyles((theme: Theme) =>
    createStyles({
        root: {
            padding: '0% 10% 0% 10%',
            display: 'flex',
            alignItems: 'center',
            flexDirection:'column',
        },
    }),
);



export interface AuthorI {
    __typename: string;
    name: string;
}

export interface PhotoI {
    __typename: string;
    uri: string;
}

export interface BookI {
    __typename: string;
    author: AuthorI;
    photos: PhotoI[];
    title: string;
}

interface BooksI {
    books: BookI[]
}

export default function Home() {
    const classes = useStyles()

    const [books, setBooks] = useState<BooksI>()
    useEffect(() => {
        client.query({query}).then((response: ApolloQueryResult<BooksI>) => {
            console.log(response.data)
            setBooks(response.data)
        });
    }, [])
// Invoke the query and log the person's name
    return (
        <div className={classes.root}>
            <Head>
                <title>Book store</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Search/>
            <Box alignSelf={'flex-start'} marginLeft={'15px'}>
                <Typography variant={'h4'}>Browse</Typography>
            </Box>
            <Box width={'100%'} display={'flex'} flexWrap={'wrap'} justifyContent={'space-between'} padding={'0 10px 0 10px'}>
                {books?.books.map((book, index)=> {
                    return (
                        <Book key={index} book={book}/>
                    )
                })}
            </Box>
        </div>
        // <Grid container={true} direction={'column'}  alignItems={'center'} >
        //
        // </Grid>
    )
}
